{% set name = "pathos" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bad4912d0ef865654a7cc478da65f2e1d5b69f3d92c4a7d9c9845657783c0754

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
  run:
    - dill >=0.4.0
    - multiprocess >=0.70.18
    - pox >=0.3.6
    - ppft >=1.7.7
    - python >={{ python_min }}

test:
  imports:
    - pathos
    - pathos.helpers
    - pathos.secure
    - pathos.xmlrpc
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/uqfoundation/pathos
  license: BSD-3-Clause
  license_file: LICENSE
  summary: parallel graph management and execution in heterogeneous computing
  dev_url: https://github.com/uqfoundation/pathos

extra:
  recipe-maintainers:
    - jschueller
    - mariusvniekerk
    - synapticarbors
