{% set name = "pathos" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f2a42bc1e10ccf0fe71961e7145fc1437018b6b21bd93b2446abc3983e49a7a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.6
  run:
    - dill >=0.3.5.1
    - multiprocess >=0.70.13
    - pox >=0.3.1
    - ppft >=1.7.6.5
    - python =2.7|>=3.6

test:
  imports:
    - pathos
    - pathos.helpers
    - pathos.secure
    - pathos.xmlrpc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/uqfoundation/pathos
  license: BSD-3-Clause
  license_file: LICENSE
  summary: parallel graph management and execution in heterogeneous computing
  dev_url: https://github.com/uqfoundation/pathos

extra:
  recipe-maintainers:
    - jschueller
    - mariusvniekerk
    - synapticarbors
