{% set name = "pathos" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dcb2a5f321aa34ca541c1c1861011ea49df357bb908379c21dd5741f666e0a58

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dill >=0.3.8
    - multiprocess >=0.70.16
    - pox >=0.3.4
    - ppft >=1.7.6.8
    - python >=3.8

test:
  imports:
    - pathos
    - pathos.helpers
    - pathos.secure
    - pathos.xmlrpc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/uqfoundation/pathos
  license: BSD-3-Clause
  license_file: LICENSE
  summary: parallel graph management and execution in heterogeneous computing
  dev_url: https://github.com/uqfoundation/pathos

extra:
  recipe-maintainers:
    - jschueller
    - mariusvniekerk
    - synapticarbors
