{% set name = "pathos" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8fe041b8545c5d3880a038f866022bdebf935e5cf68f56ed3407cb7e65193a61

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
  run:
    - dill >=0.4.1
    - multiprocess >=0.70.19
    - pox >=0.3.7
    - ppft >=1.7.8
    - python >={{ python_min }}

test:
  imports:
    - pathos
    - pathos.helpers
    - pathos.secure
    - pathos.xmlrpc
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/uqfoundation/pathos
  license: BSD-3-Clause
  license_file: LICENSE
  summary: parallel graph management and execution in heterogeneous computing
  dev_url: https://github.com/uqfoundation/pathos

extra:
  recipe-maintainers:
    - jschueller
    - mariusvniekerk
    - synapticarbors
